// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDermAssist2025KeyExample12345',
    appId: '1:1234567890123:web:abc123def456ghi789',
    messagingSenderId: '1234567890123',
    projectId: 'dermassist-2025',
    authDomain: 'dermassist-2025.firebaseapp.com',
    storageBucket: 'dermassist-2025.appspot.com',
    measurementId: 'G-MEASUREMENT123',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDermAssistAndroidKeyExample12345',
    appId: '1:1234567890123:android:abc123def456ghi789',
    messagingSenderId: '1234567890123',
    projectId: 'dermassist-2025',
    storageBucket: 'dermassist-2025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDermAssistIOSKeyExample12345',
    appId: '1:1234567890123:ios:abc123def456ghi789',
    messagingSenderId: '1234567890123',
    projectId: 'dermassist-2025',
    storageBucket: 'dermassist-2025.appspot.com',
    iosClientId: '1234567890123-ios-abc123def456ghi789.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinDiseaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDermAssistWindowsKeyExample12345',
    appId: '1:1234567890123:windows:abc123def456ghi789',
    messagingSenderId: '1234567890123',
    projectId: 'dermassist-2025',
    storageBucket: 'dermassist-2025.appspot.com',
  );
}
